
#include "pch.h"

/* NINJA Basic+ (with Sonic Adventure DX PC additions) model
 *
 * Generated by SAMDL
 *
 * Description: Character Shadow Blob
 *
 */

NJS_MATERIAL matlist_004BF2C0[] = {
	{ { 0xB0FFFFFF }, { 0x00000000 }, 0, 10, NJD_D_100 | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC }
};

Sint16 poly_004BF2D4[] = {
	0, 1, 3,
	0, 3, 2
};

NJS_TEX uv_004BF2E0[] = {
	{ 7, 247 },
	{ 7, 7 },
	{ 247, 7 },
	{ 7, 247 },
	{ 247, 7 },
	{ 247, 247 }
};

NJS_MESHSET_SADX meshlist_004BF2F8[] = {
	{ NJD_MESHSET_3 | 0, 2, poly_004BF2D4, NULL, NULL, NULL, uv_004BF2E0, NULL }
};

NJS_VECTOR vertex_004BF314[] = {
	{ -5, 0, -5 },
	{ -5, 0, 5 },
	{ 5, 0, -5 },
	{ 5, 0, 5 }
};

NJS_VECTOR normal_004BF344[] = {
	{ 0, 1, 0 },
	{ 0, 1, 0 },
	{ 0, 1, 0 },
	{ 0, 1, 0 }
};

NJS_MODEL_SADX attach_004BF374 = { vertex_004BF314, normal_004BF344, LengthOfArray<Sint32>(vertex_004BF314), meshlist_004BF2F8, matlist_004BF2C0, LengthOfArray<Uint16>(meshlist_004BF2F8), LengthOfArray<Uint16>(matlist_004BF2C0), { 0 }, 7.071068f, NULL };

NJS_OBJECT Jenny_Shadow = { NJD_EVAL_UNIT_POS | NJD_EVAL_UNIT_ANG | NJD_EVAL_UNIT_SCL | NJD_EVAL_BREAK, &attach_004BF374, 0, 0, 0, 0, 0, 0, 1, 1, 1, NULL, NULL };
